
target("Launcher")
    add_rules("win.sdk.mfc.static_app")
    set_kind("binary")
    add_files("**.cpp", '**.rc')
    add_headerfiles("**.h")
    set_pcxxheader('src/pch.h')
    add_packages('rest_rpc', 'microsoft-detours')
    -- add_deps('Monitor', {headeronly=true})
    add_includedirs('../Monitor/include')
    add_defines('UNICODE', '_UNICODE')
