
target("Monitor")
    set_suffixname(is_arch('x64') and '64' or '')
    set_kind("shared", { headeronly = true} )
    add_files("**.cpp")
    add_headerfiles("**.h")
    set_pcxxheader('src/pch.h')
    add_packages('microsoft-detours', 'veigar')
    add_includedirs('include', { public = true })
    add_links('advapi32', 'kernel32', 'ole32', 'user32')
    add_shflags('/export:DetourFinishHelperProcess')
    add_defines('MSGPACK_NO_BOOST')
